{% set data= load_setup_py_data() %}
package:
  name: ts-ess
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - PATH
    - PYTHONPATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - PYTHON_BUILD_VERSION
    - PYTHON_BUILD_LOCATION
    - TS_CONFIG_OCS_DIR
    - LSST_DDS_DOMAIN

test:
  requires:
    - pytest
    - pytest-flake8
    - pytest-cov
    - asynctest
    - pytest-tornasync
    - numpy
    - astropy
    - jsonschema
    - pyyaml
    - boto3
    - moto
    - pyserial
    - ts-simactuators
    - ts-dds
    - ts-idl
    - ts-salobj
    - black == 19.10b0
  source_files:
    - python
    - bin
    - tests
    - schema
    - setup.cfg
  commands:
    - py.test --ignore-glob=**/ESS_* --ignore-glob=**/ess_temperature_reader.py

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-salobj
    - ts-simactuators
